version: "3"

services:
  mariadb:
    image: "mariadb"
    ports:
      - 3306:3306
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "mariadb.data:/var/lib/mysql"
    environment:
      - MARIADB_USER=${MARIADB_USER:-user}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-pass}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-ssap}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-devdb}
    command: >
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
  spring:
    build: .
    ports:
      - 8080:8080
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - mariadb


volumes:
  mariadb.data:
    name: mariadb.data

networks:
  default:
    name: demo.kafka
