version: "3"

services:
  zookeeper:
    image: "zookeeper"
    ports:
      - 2181:2181
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  kafka:
    build: kafka-docker/.
    ports:
      - 9092:9092
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
        # - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "kafka_topic:1:1" # topic_name:num_of_partition:num_of_replica
      KAFKA_GROUP_ID: "kafka_group"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  mariadb:
    image: "mariadb"
    ports:
      - 3306:3306
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "mariadb.data:/var/lib/mysql"
    environment:
      - MARIADB_USER=${MARIADB_USER:-user}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-pass}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-ssap}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-devdb}
    command: >
      mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
  spring:
    build: .
    ports:
      - 8080:8080
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - mariadb


volumes:
  mariadb.data:
    name: mariadb.data

networks:
  default:
    name: demo.kafka
