spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      exclude: build/**
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOSTNAME:kafka}:${KAFKA_PORT:9092}
      group-id: kafka_group
      # auto-offset-reset: earliest
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_HOSTNAME:kafka}:${KAFKA_PORT:9092}
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://${DB_HOSTNAME:mariadb}:${DB_PORT:3306}/${DB_DATABASE:devdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}

---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/devdb
    username: user
    password: pass
